"""Search Spaces"""

search_space_MLP = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "normalize": {"_type": "choice", "_value": [-1, 1]},
    "lr": {"_type": "choice", "_value": [0.001, 0.005, 0.01, 0.05]},
    "l2_coef": {"_type": "choice", "_value": [0, 0.00005, 0.0001, 0.0005, 0.001]},
    "layers": {"_type": "choice", "_value": [1, 2, 3]},
    "patience": {"_type": "choice", "_value": [100, 200]},
    "dropout": {"_type": "choice", "_value": [0, 0.5]},
    "nhidden": {"_type": "choice", "_value": [16, 32, 64]},
}
search_space_SGC = {
    "layers": {"_type": "choice", "_value": [1, 2, 3, 4, 8, 10, 16, 32, 64]},
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "normalize": {"_type": "choice", "_value": [-1, 1]},
    "lr": {"_type": "choice", "_value": [0.001, 0.005, 0.01, 0.05]},
    "l2_coef": {"_type": "choice", "_value": [0, 0.00005, 0.0001, 0.0005, 0.001]},
    "patience": {"_type": "choice", "_value": [100, 200]},
    "dropout": {"_type": "choice", "_value": [0, 0.5]},
    "nhidden": {"_type": "choice", "_value": [16, 32, 64]},
}
search_space_GCN = {
    "layers": {"_type": "choice", "_value": [1, 2, 3, 4, 8, 10, 16, 32, 64]},
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "normalize": {"_type": "choice", "_value": [-1, 1]},
    "lr": {"_type": "choice", "_value": [0.001, 0.005, 0.01, 0.05]},
    "l2_coef": {"_type": "choice", "_value": [0, 0.00005, 0.0001, 0.0005, 0.001]},
    "patience": {"_type": "choice", "_value": [100, 200]},
    "dropout": {"_type": "choice", "_value": [0, 0.5]},
    "nhidden": {"_type": "choice", "_value": [16, 32, 64]},
}
search_space_GAT = {
    "layers": {"_type": "choice", "_value": [1, 2, 3, 4, 8, 10, 16, 32, 64]},
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "normalize": {"_type": "choice", "_value": [-1, 1]},
    "lr": {"_type": "choice", "_value": [0.001, 0.005, 0.01, 0.05]},
    "l2_coef": {"_type": "choice", "_value": [0, 0.00005, 0.0001, 0.0005, 0.001]},
    "patience": {"_type": "choice", "_value": [100, 200]},
    "dropout": {"_type": "choice", "_value": [0, 0.5]},
    "nhidden": {"_type": "choice", "_value": [16, 32, 64]},
}
search_space_GraphSAGE = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "layers": {"_type": "choice", "_value": [1, 2, 3, 4, 8, 10, 16, 32, 64]},
    "normalize": {"_type": "choice", "_value": [-1, 1]},
    "lr": {"_type": "choice", "_value": [0.001, 0.005, 0.01, 0.05]},
    "l2_coef": {"_type": "choice", "_value": [0, 0.00005, 0.0001, 0.0005, 0.001]},
    "patience": {"_type": "choice", "_value": [100, 200]},
    "dropout": {"_type": "choice", "_value": [0, 0.5]},
    "nhidden": {"_type": "choice", "_value": [16, 32, 64]},
}
search_space_APPNP = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "lr": {"_type": "choice", "_value": [0.001, 0.005, 0.01, 0.05]},
    "l2_coef": {"_type": "choice", "_value": [0, 0.0005]},
    "alpha": {"_type": "choice", "_value": [0.1, 0.2, 0.5]},
    "iterations": {"_type": "choice", "_value": [1, 2, 3, 4, 8, 10]},
    "patience": {"_type": "choice", "_value": [100, 200]},
}
search_space_JKNet = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "lr": {"_type": "choice", "_value": [0.01, 0.001]},
    "l2_coef": {"_type": "choice", "_value": [0, 0.00001, 0.00005, 0.0001, 0.0005, 0.001]},
    "dropout": {"_type": "quniform", "_value": [0.2, 0.5, 0.8]},
    "n_layers": {"_type": "choice", "_value": [1, 2, 3, 4, 8]},
    "patience": {"_type": "choice", "_value": [100, 200]},
}
search_space_IncepGCN = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "lr": {"_type": "choice", "_value": [0.01, 0.001]},
    "l2_coef": {"_type": "choice", "_value": [0, 0.00001, 0.00005, 0.0001, 0.0005, 0.001]},
    "dropout": {"_type": "quniform", "_value": [0.2, 0.5, 0.8]},
    "n_layers": {"_type": "choice", "_value": [1, 2, 3, 4, 8]},
    "patience": {"_type": "choice", "_value": [100, 200]},
}
search_space_SIGN = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "lr": {"_type": "choice", "_value": [0.01, 0.001]},
    "l2_coef": {"_type": "choice", "_value": [0, 0.00001, 0.00005, 0.0001, 0.0005, 0.001]},
    "dropout": {"_type": "quniform", "_value": [0.2, 0.5, 0.8]},
    "n_hops": {"_type": "choice", "_value": [1, 2, 3, 4, 8, 10, 16, 32, 64]},
    "patience": {"_type": "choice", "_value": [100, 200]},
}
search_space_MixHop = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "lr": {"_type": "choice", "_value": [0.001, 0.005, 0.01]},
    "l2_coef": {"_type": "choice", "_value": [0, 0.00001, 0.00005, 0.0001, 0.0005, 0.001]},
    "patience": {"_type": "choice", "_value": [100, 200]},
}
search_space_FAGCN = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "lr": [0.001, 0.005, 0.01, 0.05],
    "weight_decay": [1e-6, 1e-5, 5e-5, 1e-4, 5e-4],
    "epochs": [500, 800, 1000],
    "hidden": [16, 32, 64, 128, 256, 512],
    "dropout": [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
    "eps": [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
    "layer_num": [1, 2, 3, 5],
}
search_space_wGAT = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "attHeads": [1, 2, 4],
    "numOmega": [1, 2, 4],
    "n_channels": [32, 64, 128],
    "nlayers": [1, 2, 3],
    "dropout": [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
    "lr": [1e-4, 5e-4, 1e-3, 5e-3],
    "wd": [1e-5, 1e-4, 5e-4, 1e-3],
}
search_space_DAGNN = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "lr": {"_type": "choice", "_value": [0.01, 0.001]},
    "l2_coef": {"_type": "choice", "_value": [0, 0.00001, 0.00005, 0.0001, 0.0005, 0.001]},
    "dropout": {"_type": "quniform", "_value": [0.2, 0.5, 0.8]},
    "k": {"_type": "choice", "_value": [1, 2, 3, 4, 8, 10, 16, 32, 64]},
    "n_hidden": {"_type": "choice", "_value": [64, 128, 256, 512]},
    "patience": {"_type": "choice", "_value": [100, 200]},
}
search_space_GCNII = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "lr": {"_type": "choice", "_value": [0.005, 0.01, 0.05]},
    "l2_coef": {"_type": "choice", "_value": [0, 0.00005, 0.0001, 0.0005]},
    "dropout": {"_type": "choice", "_value": [0, 0.5]},
    "alpha": {"_type": "quniform", "_value": [0.1, 0.5, 0.1]},
    "lammbda": {"_type": "choice", "_value": [0.5, 1.0, 1.5]},
    "layers": {"_type": "choice", "_value": [1, 2, 3, 4, 8, 10, 16, 32, 64]},
    "variant": {"_type": "choice", "_value": [True, False]},
    "patience": {"_type": "choice", "_value": [100, 200]},
}
search_space_H2GCN = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "lr": {"_type": "choice", "_value": [0.001, 0.005, 0.01]},
    "l2_coef": {"_type": "choice", "_value": [0, 0.00001, 0.00005, 0.0001, 0.0005, 0.001]},
    "dropout": {"_type": "choice", "_value": [0, 0.5]},
    "use_relu": {"_type": "choice", "_value": [True, False]},
    "patience": {"_type": "choice", "_value": [100, 200]},
}
search_space_GBKGNN = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "lr": {"_type": "choice", "_value": [0.001, 0.0001, 0.00001]},
    "l2_coef": {"_type": "choice", "_value": [0.01, 0.001, 0.0001]},
    "lamda": {"_type": "quniform", "_value": [1, 64, 1]},
    "patience": {"_type": "choice", "_value": [100, 200]},
}
search_space_GGCN = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "lr": {"_type": "choice", "_value": [0.01]},
    "l2_coef": {"_type": "choice", "_value": [0, 0.00001, 0.00005, 0.0001, 0.0005, 0.001]},
    "dropout": {"_type": "quniform", "_value": [0, 0.7, 0.1]},
    "decay_rate": {"_type": "quniform", "_value": [0.0, 1.5, 0.1]},
    "nhidden": {"_type": "choice", "_value": [8, 16, 32, 64, 80]},
    "nlayers": {"_type": "choice", "_value": [1, 2, 3, 4, 8, 16, 32]},
    "use_sparse": {"_type": "choice", "_value": [True]},
    "patience": {"_type": "choice", "_value": [100, 200]},
}
search_space_GloGNN = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "lr": {"_type": "choice", "_value": [0.01, 0.005]},
    "l2_coef": {"_type": "choice", "_value": [0.00001, 0.00005, 0.0001]},
    "dropout": {"_type": "quniform", "_value": [0, 0.9, 0.1]},
    "alpha": {"_type": "choice", "_value": [0, 1, 10]},
    "beta": {"_type": "choice", "_value": [0.1, 1, 10, 100, 1000]},
    "gamma": {"_type": "quniform", "_value": [0, 0.9, 0.1]},
    "delta": {"_type": "quniform", "_value": [0, 1, 0.1]},
    "norm_layers": {"_type": "choice", "_value": [1, 2, 3]},
    "orders": {"_type": "quniform", "_value": [1, 2, 3, 4, 5, 8, 10]},
    "norm_func_id": {"_type": "choice", "_value": [1, 2]},
}
search_space_HOGGCN = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "lr": {"_type": "choice", "_value": [0.001, 0.005, 0.01]},
    "l2_coef": {"_type": "choice", "_value": [0, 0.00001, 0.00005, 0.0001, 0.0005, 0.001]},
    "patience": {"_type": "choice", "_value": [100, 200]},
}
search_space_CoGNN = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "tau0": [0.1, 0.3, 0.5, 0.7, 1.0, 2.0],
    "temp": [0.001, 0.01, 0.05, 0.1],
    "batch_size": [16, 32, 64],
    "lr": [1e-4, 5e-4, 1e-3, 5e-3],
    "dropout": [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
    "weight_decay": [0.0, 1e-5, 1e-4, 1e-3],
    "env_model_type": ["MEAN_GNN"],
    "env_num_layers": [2, 3, 4],
    "env_dim": [64, 128, 256],
    "dec_num_layers": [1, 2],
    "act_num_layers": [1, 2],
    "act_dim": [16, 32, 64],
    "batch_norm": [True, False],
    "layer_norm": [True, False],
}
search_space_GPRGNN = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "lr": {"_type": "choice", "_value": [0.002, 0.05, 0.01]},
    "l2_coef": {"_type": "choice", "_value": [0, 0.0005]},
    "alpha": {"_type": "choice", "_value": [0.1, 0.2, 0.5, 0.9]},
    "nlayers": {"_type": "choice", "_value": [1, 2, 3, 4, 8, 10, 16, 32]},
    "dprate": {"_type": "choice", "_value": [0, 0.5, 0.7]},
    "patience": {"_type": "choice", "_value": [100, 200]},
}
search_space_ACMGNN = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "lr": {"_type": "choice", "_value": [0.01, 0.05]},
    "l2_coef": {"_type": "choice", "_value": [0, 0.00001, 0.00005, 0.0001, 0.0005, 0.001]},
    "dropout": {"_type": "quniform", "_value": [0, 0.9, 0.1]},
    "structure_info": {"_type": "choice", "_value": [0, 1]},
    "variant": {"_type": "choice", "_value": [0, 1]},
    "patience": {"_type": "choice", "_value": [100, 200]},
}
search_space_OrderedGNN = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "lr": {"_type": "choice", "_value": [0.001, 0.005, 0.01]},
    "l2_coef": {"_type": "choice", "_value": [0.00000005, 0.000005, 0.0005, 0.05]},
    "dropout": {"_type": "quniform", "_value": [0, 0.4, 0.1]},
    "dropout2": {"_type": "quniform", "_value": [0, 0.4, 0.1]},
    "global_gating": {"_type": "cho ice", "_value": [True, False]},
    "num_layers_input": {"_type": "choice", "_value": [1, 2, 3]},
    "num_layers": {"_type": "choice", "_value": [1, 2, 3, 4, 8, 10, 16, 32, 64]},
    "patience": {"_type": "choice", "_value": [100, 200]},
}
search_space_N2 = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "d_model": [128, 256, 512],
    "nlayers": [1, 2, 4],
    "q_dim": [32, 64],
    "n_q": [4, 8],
    "n_pnode": [128, 256],
    "lr": [0.001, 0.01],
    "lr_step": [0.99999, 1],
    "lr_lb": [0.001],
    "dropout": [0.2, 0.4, 0.6, 0.8],
}
search_space_UniFilter = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "hid": [128, 256, 512],
    "nlayers": [3, 4],
    "lr1": [0.1, 0.15, 0.01, 0.05],
    "lr2": [0.5, 0.005],
    "wd1": [0, 5e-4, 5e-5],
    "wd2": [0, 5e-4, 1e-4],
    "dpC": [0, 0.3, 0.6, 0.9],
    "dpM": [0, 0.4, 0.6, 0.8],
    "tau": [1, 0.3, 0.6, 0.9],
    "dropout": [0.2, 0.4, 0.6, 0.8],
    "bias": ["none", "bn"],
}
search_space_NodeFormer = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "lr": {"_type": "choice", "_value": [0.01, 0.001]},
    "dropout": {"_type": "quniform", "_value": [0.2, 0.5, 0.8]},
    "nhidden": {"_type": "choice", "_value": [128]},
    "num_layers": {"_type": "choice", "_value": [1, 2, 4, 8]},
    "lambda": {"_type": "choice", "_value": [0, 0.1, 1]},
    "patience": {"_type": "choice", "_value": [100, 200]},
}
search_space_DIFFormer = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "lr": {"_type": "choice", "_value": [0.01, 0.001]},
    "dropout": {"_type": "quniform", "_value": [0.2, 0.5, 0.8]},
    "nhidden": {"_type": "choice", "_value": [32, 64, 128]},
    "num_layers": {"_type": "choice", "_value": [1, 2, 4, 8]},
    "patience": {"_type": "choice", "_value": [100, 200]},
}
search_space_SGFormer = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "lr": {"_type": "choice", "_value": [0.01, 0.001]},
    "dropout": {"_type": "quniform", "_value": [0.2, 0.5, 0.8]},
    "nhidden": {"_type": "choice", "_value": [32, 64, 128]},
    "num_layers": {"_type": "choice", "_value": [1, 2, 4, 8]},
    "graph_weight": {"_type": "choice", "_value": [0.2, 0.5, 0.8]},
    "patience": {"_type": "choice", "_value": [100, 200]},
}
search_space_GOAT = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "lr": [1e-4, 5e-4, 1e-3, 5e-3],
    "epochs": [500],
    "batch_size": [512, 1024, 2048],
    "test_batch_size": [256, 1024],
    "sizes": [[20, 10, 5]],
    "test_sizes": [[20, 10, 5]],
    "test_freq": [1, 5, 10],
    "num_workers": [4, 8],
    "conv_type": ["full"],
    "hidden_dim": [128, 256],
    "global_dim": [128],
    "num_layers": [1],
    "num_heads": [2, 4],
    "attn_dropout": [0.0, 0.1, 0.2, 0.5, 0.6, 0.7, 0.8, 0.9],
    "ff_dropout": [0.0, 0.1, 0.2, 0.5, 0.6, 0.7, 0.8, 0.9],
    "skip": [0, 1],
    "dist_count_norm": [1],
    "num_centroids": [4096],
    "hetero_train_prop": [0.0, 0.1, 0.2, 0.5, 0.6, 0.7, 0.8, 0.9],
}
search_space_Polynormer = {
    "dataset": {
        "_type": "choice",
        "_value": [
            "actor",
            "blogcatalog",
            "flickr",
            "roman-empire",
            "squirrel",
            "chameleon",
            "amazon-ratings",
            "pubmed",
            "photo",
            "wikics",
        ],
    },
    "local_epochs": [100, 200],
    "global_epochs": [800, 1000, 1500, 2000, 2500],
    "metric": ["acc"],
    "hidden_channels": [32, 60, 64, 256, 512],
    "local_layers": [5, 7, 10],
    "global_layers": [1, 2, 3, 4],
    "num_heads": [1, 2, 8, 16],
    "beta": [-1.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
    "pre_ln": [True, False],
    "lr": [3e-5, 0.001],
    "weight_decay": [0.0, 5e-5, 5e-4],
    "in_dropout": [0.1, 0.15, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
    "dropout": [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
    "global_dropout": [None, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
}
