from the_utils import csv_to_table

ROW_ORDER = [
    "MLP",
    "SGC",
    "GCN",
    "GAT",
    "GraphSAGE",
    "APPNP",
    "JKNet-GCN",
    "IncepGCN",
    "SIGN",
    "MixHop",
    "FAGCN",
    "wGAT",
    "DAGNN",
    "GCNII",
    "H2GCN",
    "GBKGNN",
    "GGCN",
    "GloGNN",
    "HOGGCN",
    "CoGNN",
    "GPRGNN",
    "ACMGCN",
    "OrderedGNN",
    "N2",
    "UniFilter",
    "NodeFormer",
    "DIFFormer",
    "SGFormer",
    "GOAT",
    "Polynormer",
    "r-IGNN",
    "a-IGNN",
    "c-IGNN",
]
COL_ORDER = [
    "actor",
    "blogcatalog",
    "flickr",
    "roman-empire",
    "squirrel",
    "chameleon",
    "amazon-ratings",
    "pubmed",
    "photo",
    "wikics",
]

df = csv_to_table(
    raw_path="results/add.csv",
    save_path="results/table_all.csv",
    row_key="model",
    col_key="dataset",
    val_key="acc",
    fillna=0,
    row_order=ROW_ORDER,
    col_order=COL_ORDER,
    average_rank=True,
    bold_max=True,
    save_latex=True,
)
